projects:
  shorty:
    schemaPath: amplify/backend/api/shorty/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/graphql/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/graphql/API.ts
        docsFilePath: src/graphql
        region: eu-north-1
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
